version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: pirate_chase_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pirate_chase_backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - OPENAI_API_KEY=${OPENAI_API_KEY} # Injetado pelo host
    depends_on:
      - redis
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile # Usaremos um Dockerfile para o frontend também
    container_name: pirate_chase_frontend
    ports:
      - "5173:5173" # Porta padrão do Vite
    environment:
      - VITE_API_URL=ws://localhost:8000/ws
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules # Evita que o node_modules local sobrescreva o do container

volumes:
  redis_data:
    driver: local
